{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "cveMetadata": {
        "state": "PUBLISHED",
        "cveId": "CVE-2023-28858",
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "dateUpdated": "2023-03-26T00:00:00",
        "dateReserved": "2023-03-26T00:00:00",
        "datePublished": "2023-03-26T00:00:00"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre",
                "dateUpdated": "2023-03-26T00:00:00"
            },
            "descriptions": [
                {
                    "lang": "en",
                    "value": "redis-py before 4.5.3, as used in ChatGPT and other products, leaves a connection open after canceling an async Redis command at an inopportune time (in the case of a pipeline operation), and can send response data to the client of an unrelated request in an off-by-one manner. The fixed versions for this CVE Record are 4.3.6, 4.4.3, and 4.5.3; however, CVE-2023-28859 is a separate vulnerability."
                }
            ],
            "affected": [
                {
                    "vendor": "n/a",
                    "product": "n/a",
                    "versions": [
                        {
                            "version": "n/a",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "references": [
                {
                    "url": "https://github.com/redis/redis-py/pull/2641"
                },
                {
                    "url": "https://github.com/redis/redis-py/issues/2624"
                },
                {
                    "url": "https://github.com/redis/redis-py/compare/v4.5.2...v4.5.3"
                },
                {
                    "url": "https://github.com/redis/redis-py/compare/v4.4.2...v4.4.3"
                },
                {
                    "url": "https://github.com/redis/redis-py/compare/v4.3.5...v4.3.6"
                },
                {
                    "url": "https://openai.com/blog/march-20-chatgpt-outage"
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "text",
                            "lang": "en",
                            "description": "n/a"
                        }
                    ]
                }
            ]
        }
    }
}